Repository US-EPA-CAMD/easey-campd-ui, pull requests merged in 2021-11, with the labels that each got.

#159 added tutorials page
  src/components/App/App.js
  src/components/BulkDataFiles/BulkDataFiles.js
  src/components/TutorialsPage/TutorialsPage.js
  src/components/TutorialsPage/TutorialsPage.test.js
  src/utils/constants/menuTopics.js
Labels: Datateers

#160 feature/2109-narrow-emissions-filters-based-on-timeperiod
  src/components/MultiSelectCombobox/MultiSelectCombobox.js
  src/components/MultiSelectCombobox/MultiSelectCombobox.test.js
  src/components/filterCriteria/AccountNameNumber/AccountNameNumber.test.js
  src/components/filterCriteria/Facility/Facility.test.js
  src/components/filterCriteria/OwnerOperator/OwnerOperator.test.js
  src/components/filterCriteria/Program/Program.js
  src/components/filterCriteria/SourceCategory/SourceCategory.test.js
  src/components/filterCriteria/StateTerritory/StateTerritory.test.js
  src/components/filterCriteria/TransactionType/TransactionType.test.js
  src/components/filterCriteria/timePeriod/TimePeriod/TimePeriod.js
  src/store/actions/actionTypes.js
  src/store/actions/customDataDownload/filterCriteria.js
  src/store/actions/customDataDownload/filterCriteria.test.js
  src/store/reducers/customDataDownload/filterCriteria.js
  src/utils/constants/emissions.js
  src/utils/selectors/filterCriteria.js
  src/utils/selectors/filterLogic.js
Labels: Datateers

#161 feature/2068-emissions-state-filter-logic
  src/components/dataPreview/ManageDataPreview/ManageDataPreview.js
  src/components/filterCriteria/StateTerritory/StateTerritory.js
  src/components/filterCriteria/StateTerritory/StateTerritory.test.js
  src/utils/selectors/filterCriteria.js
  src/utils/selectors/filterLogic.js
Labels: Datateers

#162 Feature/1821 related resources
  src/components/App/App.js
  src/components/App/App.test.js
  src/components/BulkDataFiles/BulkDataFiles.test.js
  src/components/DataLandingPage/DataLandingPage.test.js
  src/components/HomePage/HomePage.test.js
  src/components/RelatedResources/RelatedResources.js
  src/components/RelatedResources/RelatedResources.test.js
  src/components/TutorialsPage/TutorialsPage.test.js
  src/utils/constants/menuTopics.js
Labels: Datateers

#163 feature/2066-engaged-filter-logic-for-emissions-program
  src/components/dataPreview/ManageDataPreview/ManageDataPreview.js
  src/components/filterCriteria/Program/Program.js
  src/components/filterCriteria/Program/Program.test.js
  src/components/filterCriteria/timePeriod/TimePeriod/TimePeriod.js
  src/store/actions/customDataDownload/filterCriteria.test.js
  src/utils/selectors/filterCriteria.js
  src/utils/selectors/filterLogic.js
Labels: Datateers

#164 Feature/1609 FAQs page
  src/additional-scss/_uswds-global-overrides.scss
  src/components/App/App.js
  src/components/FaqPage/FaqsPage.js
  src/components/FaqPage/FaqsPage.test.js
  src/components/RelatedResources/RelatedResources.js
  src/components/TutorialsPage/TutorialsPage.js
  src/utils/constants/menuTopics.js
Labels: Datateers

#165 Bug/2263 faq page
  src/components/FaqPage/FaqsPage.js
  src/components/RelatedResources/RelatedResources.test.js
Labels: Datateers

#168 feature/boost-test-coverage
  src/utils/selectors/filterLogic.test.js
Labels: Datateers

#167 Task/unit test coverage
  src/components/WideHeader/WideHeader.test.js
  src/components/customDataDownload/DownloadFileType/DownloadFileType.test.js
  src/components/filterCriteria/FilterCriteriaMenu/FilterCriteriaMenu.test.js
Labels: Datateers

#169 Wip/upgrading versions
  .github/workflows/develop-branch.yml
  .github/workflows/feature-branch.yml
  .github/workflows/release-branch.yml
  .npmrc
  .yarnrc
  package-lock.json
  package.json
  src/components/App/App.js
  src/components/ContactUsPage/ContactUsPage.js
  src/components/DynamicTabs/DynamicTabs.js
  src/components/DynamicTabs/DynamicTabs.scss
  src/components/DynamicTabs/DynamicTabs.test.js
  src/components/Layout/Layout.js
  src/components/WideHeader/WideHeader.js
  src/utils/constants/menuTopics.js
  yarn.lock
Labels: Datateers, Tech Team

#171 Feature/2071-engage-filter-logic-for-emissions-fuel-type
  src/components/filterCriteria/FuelType/FuelType.js
  src/utils/selectors/filterLogic.js
Labels: Datateers

#170 Feature/1654-link-landing-page-from-home-page
  src/components/HomePage/HomePage.js
  src/components/SubHeaderInfo/SubHeaderInfo.js
Labels: Datateers

#172 Bug/2144-iron-&-steel-not-working-on-custom-data-download
  src/utils/selectors/filterCriteria.js
  src/utils/selectors/general.js
Labels: Datateers

#174 Feature/2228 select all functionality
  src/components/CheckboxGroup/CheckboxGroup.js
  src/components/filterCriteria/AccountType/AccountType.js
  src/components/filterCriteria/ControlTechnology/ControlTechnology.js
  src/components/filterCriteria/FuelType/FuelType.js
  src/components/filterCriteria/UnitType/UnitType.js
Labels: Datateers

#175 Bug/2289 select all time period
  src/components/CheckboxGroup/CheckboxGroup.js
  src/components/filterCriteria/timePeriod/TimePeriodYear/TimePeriodYear.js
Labels: Datateers

#176 Feature/2069-filter-logic-for-emissions-facility
  src/components/DynamicTabs/DynamicTabs.js
  src/components/DynamicTabs/DynamicTabs.scss
  src/components/DynamicTabs/DynamicTabs.test.js
  src/components/TabPane/TabPane.js
  src/components/TabPane/TabPane.scss
  src/components/Tabs/Tabs.js
  src/components/Tabs/Tabs.scss
  src/components/Tabs/Tabs.test.js
  src/components/filterCriteria/Facility/Facility.js
  src/components/filterCriteria/FuelType/FuelType.test.js
  src/utils/selectors/filterCriteria.js
  src/utils/selectors/filterLogic.js
Labels: Datateers

#177 Feature/2070 filter logic unit type
  src/components/filterCriteria/UnitType/UnitType.js
  src/utils/selectors/filterLogic.js
Labels: Datateers

#178 Bug/1999-Year-Component-Validation
  src/components/filterCriteria/timePeriod/TimePeriod/TimePeriod.js
  src/utils/dateValidation/dateValidation.js
Labels: Datateers

#179 Feature/2072-filter-logic-for-emissions-control-technology
  src/components/filterCriteria/ControlTechnology/ControlTechnology.js
  src/utils/constants/emissions.js
  src/utils/selectors/filterCriteria.js
  src/utils/selectors/filterLogic.js
Labels: Datateers

#181 Feature/2257 exit link related resources
  src/components/RelatedResources/RelatedResources.js
  src/components/RelatedResources/RelatedResources.test.js
Labels: Datateers

#183 Api-Key-Config
  src/components/customDataDownload/DownloadFileType/DownloadFileType.js
  src/config.js
  src/utils/api/axiosSetup.js
  src/utils/api/dataPreviewApi.js
  src/utils/api/filterCriteriaApi.js
Labels: Emissioners, Tech Team

#184 Feature/2073-emissions-source-category-filter-logic
  src/components/filterCriteria/ControlTechnology/ControlTechnology.js
  src/components/filterCriteria/ControlTechnology/ControlTechnology.test.js
  src/components/filterCriteria/FuelType/FuelType.js
  src/components/filterCriteria/FuelType/FuelType.test.js
  src/components/filterCriteria/Program/Program.js
  src/components/filterCriteria/Program/Program.test.js
  src/components/filterCriteria/SourceCategory/SourceCategory.js
  src/components/filterCriteria/UnitType/UnitType.js
  src/components/filterCriteria/UnitType/UnitType.test.js
  src/utils/selectors/filterLogic.js
  src/utils/selectors/filterLogic.test.js
Labels: Datateers

#180 Feature/1943-Improve-search-on-combo-boxes
  src/components/MultiSelectCombobox/MultiSelectCombobox.js
Labels: Datateers

#185 Bug/2299-Link-to-Data-Landing-Page-From-Home-Page-508-Issue
  src/components/HomePage/HomePage.js
Labels: Datateers

#186 Feature/2299-data-landing-page-link
  src/components/filterCriteria/FilterCriteriaPanel/filterCriteriaPanel.test.js
  src/store/reducers/customDataDownload/filterCriteria.test.js
Labels: Datateers

#187 Feature/1819-CAMPD-About-Page-Dummy-Data
  src/components/AboutPage/AboutPage.js
  src/components/AboutPage/AboutPage.test.js
  src/components/App/App.js
  src/utils/constants/menuTopics.js
Labels: Datateers

#189 Feature/1819-CAMPD-About-Page-Dummy-Data
  src/components/AboutPage/AboutPage.js
  src/components/AboutPage/AboutPage.test.js
Labels: Datateers

#190 Feature/1819-CAMPD-About-Page-Dummy-Data
  src/components/AboutPage/AboutPage.js
  src/components/AboutPage/AboutPage.test.js
  src/components/App/App.js
  src/utils/constants/menuTopics.js
Labels: Datateers

#191 Feature/1819-CAMPD-About-Page-Dummy-Data
  src/components/AboutPage/AboutPage.js
Labels: Datateers

#192 Feature/2229-filter-logic-by-program-for-allowance-subtypes
  src/components/customDataDownload/ManageDataDownload/ManageDataDownload.js
  src/utils/selectors/filterLogic.js
Labels: Datateers
