Repository US-EPA-CAMD/easey-campd-ui, pull requests merged in 2021-12, with the labels that each got.

#194 feature/2231-filter-logic-by-account-numbers-for-allowance-subtypes
  src/components/filterCriteria/AccountNameNumber/AccountNameNumber.js
  src/utils/selectors/filterLogic.js
Labels: Datateers

#193 Feature/1933 contact us
  src/components/ContactUsPage/ContactUsPage.js
  src/components/ContactUsPage/ContactUsPage.scss
  src/components/ContactUsPage/ContactUsPage.test.js
  src/components/FaqPage/FaqsPage.js
  src/components/TutorialsPage/TutorialsPage.js
  src/config.js
  src/utils/api/apiUtils.js
  src/utils/api/quartzApi.js
Labels: Datateers

#195 Feature/2282Build Reusable/ Accessible component for tool tips
  src/components/Tooltip/Tooltip.js
  src/components/Tooltip/Tooltip.scss
  src/components/customDataDownload/DataTypeSelectorView/DataTypeSelectorView.js
Labels: Datateers

#196 Feature/2231-filter-logic-by-account-numbers-for-allowance-subtypes
  src/utils/selectors/filterLogic.js
Labels: Datateers

#197 footer issue fixed
  src/components/Layout/Layout.js
Labels: bug

#199 Added google analytics connection
  package.json
  src/components/customDataDownload/DownloadFileType/DownloadFileType.js
  src/config.js
  src/index.js
  yarn.lock
Labels: Emissioners, Tech Team

#200 Feature/2182-Update-CAMPD-Sub-Header-And-Utility-Nav
  src/additional-scss/_uswds-global-overrides.scss
  src/components/Layout/Layout.js
  src/components/Layout/Layout.scss
  src/components/SubHeader/SubHeader.js
  src/components/SubHeaderNav/SubHeaderNav.js
  src/components/SubHeaderNav/SubHeaderNav.scss
  src/utils/constants/menuTopics.js
Labels: Datateers

#202 Feature/1572 easey design system
  src/components/ContactUsPage/ContactUsPage.js
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Footer/Footer.test.js
  src/components/FooterMenu/FooterMenu.js
  src/components/FooterMenu/FooterMenu.scss
  src/components/FooterMenu/FooterMenu.test.js
  src/components/RelatedResources/RelatedResources.js
  src/components/WideHeader/WideHeader.js
  src/components/WideHeader/WideHeader.scss
  src/components/WideHeader/WideHeader.test.js
  src/components/WideHeaderMenu/WideHeaderMenu.js
  src/components/WideHeaderMenu/WideHeaderMenu.scss
  src/components/WideHeaderMenu/WideHeaderMenu.test.js
  src/utils/constants/menuTopics.js
  src/utils/selectors/filterCriteria.js
  src/utils/selectors/filterLogic.js
  src/utils/selectors/filterLogic.test.js
Labels: Datateers

#201 Removed key
  src/config.js
Labels: Emissioners, Tech Team

#204 Feature/2250-convert-allowance-holdings-vintage-year-filter
  src/components/SubHeader/SubHeader.test.js
  src/components/customDataDownload/ManageDataDownload/ManageDataDownload.js
  src/components/filterCriteria/FilterCriteriaPanel/FilterCriteriaPanel.js
  src/components/filterCriteria/timePeriod/TimePeriodComboBox/TimePeriodComboBox.js
  src/components/filterCriteria/timePeriod/TimePeriodComboBox/TimePeriodComboBox.test.js
  src/store/reducers/initialState.js
  src/utils/selectors/filterCriteria.js
  src/utils/selectors/timePeriodQuery.js
Labels: Datateers

#203 Devops-Additions
  .github/workflows/develop-branch.yml
  .github/workflows/release-branch.yml
  manifest-vars.prod.yml
  manifest-vars.yml
  manifest.yml
  package.json
  yarn.lock
Labels: Emissioners, Tech Team

#205 Bug/2341-CAMPD-About-Page-508-Issue
  src/components/AboutPage/AboutPage.js
Labels: Datateers

#206 Feature/2250-convert-allowance-holdings-vintage-year-filter
  src/components/FilterTags/FilterTags.js
  src/components/filterCriteria/timePeriod/TimePeriodComboBox/TimePeriodComboBox.js
  src/config.js
  src/utils/constants/allowances.js
  src/utils/selectors/filterLogic.js
Labels: Datateers

#207 Bug/2341-CAMPD-About-Page-508-Issue
  src/components/AboutPage/AboutPage.js
Labels: Datateers

#208 Test-Coverage
  src/utils/api/quartzApi.test.js
Labels: Emissioners, Tech Team

#209 Test-Coverage
  src/utils/api/quartzApi.test.js
  src/utils/ensure-508/rdt-table.test.js
Labels: Emissioners, Tech Team

#210 Bug/2349-update CAMPD Sub Header and utility nav
  src/components/Layout/Layout.scss
  src/components/SubHeader/SubHeader.js
Labels: Datateers

#211 Bug/2349 update campd sub header and utility nav
  src/components/Layout/Layout.scss
Labels: Datateers

#213 Feature/2298-CAMPD-FAQ-Page-508-Issue
  src/components/AboutPage/AboutPage.js
  src/components/AboutPage/AboutPage.test.js
  src/components/FaqPage/FaqsPage.js
  src/utils/ensure-508/formatAccordionTitles.js
Labels: Datateers

#214 508 issues fixed
  package.json
  yarn.lock
Labels: bug

#215 Feature/2235 Engage filter logic by vintage year- allowance sub types
  src/components/filterCriteria/timePeriod/TimePeriodComboBox/TimePeriodComboBox.js
  src/utils/selectors/filterLogic.js
Labels: Datateers

#216 Feature/2233-Engage-Filter-Logic-By-Owner/operator-Allowance-Sub-Types
  src/components/filterCriteria/OwnerOperator/OwnerOperator.js
  src/utils/selectors/filterLogic.js
Labels: Datateers

#217 Feature/2237-engage-filter-logic-by-program-for-compliance-subtypes
  src/components/FilterTags/FilterTags.js
  src/components/customDataDownload/ManageDataDownload/ManageDataDownload.js
  src/components/dataPreview/ManageDataPreview/ManageDataPreview.js
  src/components/filterCriteria/FilterCriteriaPanel/FilterCriteriaPanel.js
  src/components/filterCriteria/Program/Program.js
  src/components/filterCriteria/timePeriod/TimePeriodComboBox/TimePeriodComboBox.js
  src/utils/api/filterCriteriaApi.js
  src/utils/constants/allowances.js
  src/utils/constants/compliances.js
  src/utils/selectors/filterCriteria.js
  src/utils/selectors/filterLogic.js
Labels: Datateers

#220 Bug/2353 contact us 508 issue
  package.json
  src/components/ContactUsPage/ContactUsPage.js
  src/components/ContactUsPage/ContactUsPage.scss
  yarn.lock
Labels: Datateers

#221 Feat/global fonts
  package.json
  public/index.html
  src/additional-scss/_global-overrides.scss
  src/additional-scss/_global-styles.scss
  src/additional-scss/_variables.scss
  src/components/App/App.scss
Labels: Datateers

#225 Feature/2238-filter-logic-by-facility-for-compliance-sub-types
  src/components/customDataDownload/ManageDataDownload/ManageDataDownload.js
  src/components/dataPreview/ManageDataPreview/ManageDataPreview.js
  src/components/filterCriteria/Facility/Facility.js
  src/utils/selectors/filterLogic.js
  src/utils/selectors/filterLogic.test.js
Labels: Datateers

#224 Feature/2240 compliance states filter logic
  src/components/ContactUsPage/ContactUsPage.js
  src/components/filterCriteria/StateTerritory/StateTerritory.js
Labels: Datateers

#226 Feature/2343-disable-filters-that-do-not-contain-selectable-data
  src/components/DataLandingPage/DataLandingPage.js
  src/components/HomePage/HomePage.js
  src/components/customDataDownload/ManageDataDownload/ManageDataDownload.js
  src/components/filterCriteria/FilterCriteriaMenu/FilterCriteriaMenu.js
Labels: Datateers

#227 Bug/2354 Reusable component for tool tips - 508 issue
  src/components/Tooltip/Tooltip.js
  src/components/customDataDownload/DataTypeSelectorView/DataTypeSelectorView.js
Labels: Datateers

#228 Feature/2239-Engage-Filter-Logic-By-Owner/-Operator-Compliance-Sub-Types
  src/components/filterCriteria/OwnerOperator/OwnerOperator.js
Labels: Datateers

#229 Feature/2343-disable-filters-that-do-not-contain-selectable-data
  src/components/filterCriteria/FilterCriteriaMenu/FilterCriteriaMenu.js
Labels: Datateers

#230 feature/2236-engage-filter-logic-by-all-filters-except-transaction-type-for-transactions-subtype
  src/components/dataPreview/ManageDataPreview/ManageDataPreview.js
  src/components/filterCriteria/AccountNameNumber/AccountNameNumber.js
  src/components/filterCriteria/Facility/Facility.js
  src/components/filterCriteria/FilterCriteriaMenu/FilterCriteriaMenu.js
  src/components/filterCriteria/FilterCriteriaPanel/FilterCriteriaPanel.js
  src/components/filterCriteria/Program/Program.js
  src/components/filterCriteria/StateTerritory/StateTerritory.js
  src/components/filterCriteria/timePeriod/TimePeriod/TimePeriod.js
  src/components/filterCriteria/timePeriod/TimePeriodComboBox/TimePeriodComboBox.js
  src/store/actions/customDataDownload/filterCriteria.js
  src/utils/api/filterCriteriaApi.js
  src/utils/constants/allowances.js
  src/utils/selectors/filterCriteria.js
  src/utils/selectors/filterLogic.js
  src/utils/selectors/timePeriodQuery.js
Labels: Datateers

#231 feature/2236-engaged-filter-logic-by-transaction-type
  src/components/filterCriteria/TransactionType/TransactionType.js
  src/utils/selectors/filterCriteria.js
  src/utils/selectors/filterLogic.js
Labels: Datateers

#233 Feature/2241-Engage-Filter-Logic-By-Year-Compliance-Sub-Types
  src/components/filterCriteria/timePeriod/TimePeriodComboBox/TimePeriodComboBox.js
  src/utils/selectors/filterLogic.js
Labels: Datateers

#234 Feature/1942 utilize white space
  src/components/App/App.js
  src/components/DataLandingPage/DataLandingPage.js
  src/components/HomePage/HomePage.js
  src/components/SelectDataType/SelectDataType.js
  src/components/SelectDataType/SelectDataType.scss
  src/components/SelectDataType/SelectDataType.test.js
  src/components/SubHeader/SubHeader.js
  src/components/customDataDownload/DataTypeSelectorView/DataTypeSelectorView.js
  src/components/customDataDownload/ManageDataDownload/ManageDataDownload.js
  src/components/dataPreview/ManageDataPreview/ManageDataPreview.js
  src/components/protectedRoutes/ManageDataDownloadRoute/ManageDataDownloadRoute.js
  src/components/protectedRoutes/ManageDataDownloadRoute/ManageDataDownloadRoute.test.js
  src/utils/constants/menuTopics.js
Labels: Datateers

#235 Feature/1910 update campd tooltips
  src/components/Tooltip/Tooltip.scss
  src/components/customDataDownload/DataTypeSelectorView/DataTypeSelectorView.js
  src/components/dataPreview/ManageDataPreview/ManageDataPreview.js
  src/components/filterCriteria/AccountNameNumber/AccountNameNumber.js
  src/components/filterCriteria/AccountType/AccountType.js
  src/components/filterCriteria/ControlTechnology/ControlTechnology.js
  src/components/filterCriteria/Facility/Facility.js
  src/components/filterCriteria/FilterCriteriaMenu/FilterCriteriaMenu.js
  src/components/filterCriteria/FuelType/FuelType.js
  src/components/filterCriteria/OwnerOperator/OwnerOperator.js
  src/components/filterCriteria/Program/Program.js
  src/components/filterCriteria/SourceCategory/SourceCategory.js
  src/components/filterCriteria/StateTerritory/StateTerritory.js
  src/components/filterCriteria/TransactionType/TransactionType.js
  src/components/filterCriteria/UnitType/UnitType.js
  src/components/filterCriteria/timePeriod/TimePeriod/TimePeriod.js
  src/components/filterCriteria/timePeriod/TimePeriod/TimePeriodRender.js
  src/components/filterCriteria/timePeriod/TimePeriodComboBox/TimePeriodComboBox.js
  src/components/filterCriteria/timePeriod/TimePeriodFullDate/TimePeriodFullDate.js
  src/utils/constants/customDataDownload.js
Labels: Datateers

#236 updated wording for time period tooltip
  src/components/filterCriteria/timePeriod/TimePeriod/TimePeriodRender.js
Labels: Datateers

#238 feature/2425-bug-filter-logic-by-transaction-type
  src/components/dataPreview/ManageDataPreview/ManageDataPreview.js
  src/components/filterCriteria/timePeriod/TimePeriod/TimePeriod.js
  src/store/actions/customDataDownload/filterCriteria.js
  src/utils/selectors/filterCriteria.js
  src/utils/selectors/filterLogic.js
  src/utils/selectors/general.js
Labels: Datateers

#239 Bug/2110-Custom-Data-Download-Retains-Filter-Criteria-After-Leaving-The-Tool
  src/components/customDataDownload/ManageDataDownload/ManageDataDownload.js
Labels: Datateers

#237 Added-Progress
  package.json
  src/components/HomePage/HomePage.js
  src/utils/api/getSubmissionProgress.js
  yarn.lock
Labels: Emissioners, Tech Team

#240 Feature-2432-bug-filter-logic-year-vintage-year-component
  src/utils/selectors/filterCriteria.js
Labels: Datateers

#242 Feature/2187-bulk-data-files-508-bug
  src/components/BulkDataFiles/BulkDataFiles.js
Labels: Datateers

#243 Feature/2375-Code-Clean-Up-PI-6
  src/components/MultiSelectCombobox/MultiSelectCombobox.js
  src/components/SelectableCards/SelectableCards.js
  src/components/SelectableCards/SelectableCards.scss
  src/components/Tooltip/Tooltip.js
  src/components/customDataDownload/ManageDataDownload/ManageDataDownload.test.js
  src/components/filterCriteria/FilterCriteriaMenu/FilterCriteriaMenu.test.js
  src/store/actions/customDataDownload/filterCriteria.test.js
  src/store/reducers/initialState.js
Labels: Datateers
