Repository US-EPA-CAMD/easey-campd-ui, pull requests merged in 2021-07, with the labels that each got.

#76 Feature/1163 quarterly data preview
  src/components/dataPreview/ManageDataPreview/ManageDataPreview.js
  src/components/dataPreview/QuarterlyEmissions/QuarterlyEmissions.js
  src/store/actions/actionTypes.js
  src/store/actions/customDataDownload/customDataDownload.js
  src/store/reducers/customDataDownload/customDataDownload.js
  src/utils/api/emissionsApi.js
  src/utils/selectors/emissions.js
Labels: Datateers

#77 Feature/1561 add menu items to campd subheader
  public/images/icons/Collapse.svg
  public/images/icons/Expand.svg
  public/images/icons/mobile-menu-collapse.svg
  public/images/icons/mobile-menu-expand.svg
  src/additional-scss/_uswds-global-overrides.scss
  src/components/SubHeader/SubHeader.js
  src/utils/constants/menuTopics.js
Labels: Datateers

#79 Feature/1591 bug home page
  src/components/HomePage/HomePage.js
  src/components/Layout/Layout.scss
  src/components/SelectDataType/SelectDataType.scss
  src/components/SelectableCards/SelectableCards.js
  src/components/SubHeader/SubHeader.js
  src/utils/constants/menuTopics.js
Labels: Datateers

#80 Feature/page title additional 508 fixes
  src/components/FooterMenu/FooterMenu.js
  src/components/HomePage/HomePage.js
  src/components/SelectDataType/SelectDataType.js
  src/components/WideHeader/WideHeader.js
  src/components/customDataDownload/ManageDataDownload/ManageDataDownload.js
  src/components/filterCriteria/timePeriod/TimePeriod/TimePeriod.js
  src/utils/selectors/general.js
Labels: Datateers

#81 Feature/1202 ozone and annual emissions data preview
  src/components/dataPreview/AnnualEmissions/AnnualEmissions.js
  src/components/dataPreview/ManageDataPreview/ManageDataPreview.js
  src/components/filterCriteria/timePeriod/TimePeriod/TimePeriod.js
  src/store/actions/actionTypes.js
  src/store/actions/customDataDownload/customDataDownload.js
  src/store/reducers/customDataDownload/customDataDownload.js
  src/utils/api/emissionsApi.js
  src/utils/selectors/emissions.js
  src/utils/selectors/general.js
Labels: Datateers

#83 Bug/1587 clear checkbox state
  src/components/filterCriteria/timePeriod/TimePeriod/TimePeriod.js
  src/utils/selectors/emissions.js
Labels: Datateers

#84 Feature/1602 bug campd home page
  src/components/HomePage/HomePage.js
Labels: Datateers

#85 Bug/1607-fix-quarter-label
  src/components/dataPreview/QuarterlyEmissions/QuarterlyEmissions.js
Labels: Datateers

#86 Bug/1614 annual validation
  src/components/filterCriteria/FilterCriteriaPanel/FilterCriteriaPanel.js
  src/components/filterCriteria/timePeriod/TimePeriod/TimePeriod.js
  src/components/filterCriteria/timePeriod/TimePeriod/TimePeriodRender.js
  src/components/filterCriteria/timePeriod/TimePeriodYear/TimePeriodYear.js
  src/utils/dateValidation/dateValidation.js
Labels: Datateers

#87 Unit Test Coverage/Data Preview
  src/components/dataPreview/DataPreviewRender/DataPreviewRender.test.js
  src/components/dataPreview/ManageDataPreview/ManageDataPreview.test.js
  src/components/filterCriteria/timePeriod/TimePeriod/TimePeriod.test.js
  src/store/actions/customDataDownload/customDataDownload.test.js
Labels: Datateers

#88 fix code smells
  src/components/DynamicTabs/DynamicTabs.js
  src/components/TableBody/TableBody.js
  src/components/TableCell/TableCell.scss
  src/components/TableHeader/TableHeader.scss
  src/components/WideHeader/WideHeader.js
  src/components/filterCriteria/timePeriod/TimePeriod/TimePeriod.js
  src/components/filterCriteria/timePeriod/TimePeriod/TimePeriodRender.js
  src/store/reducers/customDataDownload/customDataDownload.js
  src/utils/api/emissionsApi.js
  src/utils/remoteLogging.js
Labels: Datateers

#89 Feature/1519 campd data landing page
  src/components/App/App.js
  src/components/DataLandingPage/DataLandingPage.js
  src/components/DataLandingPage/DataLandingPage.scss
  src/components/DataLandingPage/DataLandingPage.test.js
  src/components/HomePage/HomePage.js
  src/utils/constants/menuTopics.js
Labels: Datateers

#90 Feature/1531 implement tooltips
  src/components/customDataDownload/DataTypeSelectorRender/DataTypeSelectorRender.js
  src/components/dataPreview/ManageDataPreview/ManageDataPreview.js
  src/components/filterCriteria/FilterCriteriaMenu/FilterCriteriaMenu.js
Labels: Datateers

#91 Feature/1062 date range validation
  src/components/filterCriteria/timePeriod/TimePeriod/TimePeriod.js
  src/components/filterCriteria/timePeriod/TimePeriodFullDate/TimePeriodFullDate.js
  src/utils/dateValidation/dateValidation.js
Labels: Datateers

#92 Feature/1531 add tooltip
  src/components/SelectableCards/SelectableCards.js
Labels: Datateers

#93 Feature/1531 fix tooltip wording
  src/components/dataPreview/ManageDataPreview/ManageDataPreview.js
Labels: Datateers

#94 Feature/1500 select data type page responsiveness
  src/components/DataLandingPage/DataLandingPage.test.js
  src/components/SelectDataType/SelectDataType.js
  src/components/SelectDataType/SelectDataType.scss
  src/components/SelectableCards/SelectableCards.js
  src/components/SelectableCards/SelectableCards.scss
Labels: Datateers

#95 Feature/1588 utility nav
  src/additional-scss/_uswds-global-overrides.scss
  src/components/SubHeader/SubHeader.js
  src/components/SubHeader/SubHeader.scss
  src/components/SubHeaderNav/SubHeaderNav.js
  src/components/SubHeaderNav/SubHeaderNav.scss
  src/utils/constants/menuTopics.js
Labels: Datateers

#97 Feature/1696 Bug campd data landing page
  src/components/DataLandingPage/DataLandingPage.js
Labels: Datateers

#96 Feature/1588-fix-link
  src/components/App/App.js
  src/config.js
  src/utils/constants/menuTopics.js
Labels: Datateers

#99 Feature/1588 fix menu link issue
  src/components/SubHeaderNav/SubHeaderNav.js
Labels: Datateers

#98 Feature/1619 filter panel responsiveness
  src/components/customDataDownload/ManageDataDownload/ManageDataDownload.js
Labels: Datateers

#100 Release pipeline
  .github/workflows/develop-branch.yml
  .github/workflows/feature-branch.yml
  .github/workflows/release-branch.yml
  .github/workflows/staging-deployment.yml
  .github/workflows/test-deployment.yml
Labels: DevOps, Tech Team

#101 Feature/1461 title side bar responsivness
  src/components/Layout/Layout.scss
  src/components/SubHeader/SubHeader.js
  src/components/customDataDownload/DataTypeSelectorView/DataTypeSelectorView.js
  src/components/customDataDownload/ManageDataDownload/ManageDataDownload.js
  src/components/customDataDownload/ManageDataDownload/ManageDataDownload.scss
  src/components/dataPreview/ManageDataPreview/ManageDataPreview.js
  src/components/dataPreview/ManageDataPreview/ManageDataPreview.scss
  src/components/filterCriteria/FilterCriteriaPanel/FilterCriteriaPanel.js
Labels: Datateers

#102 Feature/1461 title side bar responsivness
  src/components/customDataDownload/ManageDataDownload/ManageDataDownload.js
  src/components/customDataDownload/ManageDataDownload/ManageDataDownload.scss
  src/components/dataPreview/ManageDataPreview/ManageDataPreview.js
Labels: Datateers

#104 feature/103-Update-README-files-in-repos-with-disclaimer
  README.md
Labels: Tech Team

#105 Feature/1104 account type
  src/components/CheckboxGroupRenderer/CheckboxGroupRenderer.js
  src/components/CheckboxGroupRenderer/CheckboxGroupRenderer.test.js
  src/components/DataLandingPage/DataLandingPage.test.js
  src/components/UnitCheckboxRenderer/UnitCheckboxRenderer.js
  src/components/UnitCheckboxRenderer/UnitCheckboxRenderer.test.js
  src/components/filterCriteria/AccountType/AccountType.js
  src/components/filterCriteria/AccountType/AccountType.test.js
  src/components/filterCriteria/ControlTechnology/ControlTechnology.js
  src/components/filterCriteria/FilterCriteriaPanel/FilterCriteriaPanel.js
  src/components/filterCriteria/FuelType/FuelType.js
  src/components/filterCriteria/Program/Program.js
  src/components/filterCriteria/UnitType/UnitType.js
  src/store/actions/actionTypes.js
  src/store/actions/customDataDownload/customDataDownload.js
  src/store/actions/customDataDownload/filterCriteria.js
  src/store/reducers/customDataDownload/filterCriteria.js
  src/store/reducers/initialState.js
  src/utils/api/filterCriteriaApi.js
  src/utils/constants/allowances.js
  src/utils/selectors/filterCriteria.js
Labels: Datateers

#107 Feature/1102 vintage year
  src/components/FilterTags/FilterTags.js
  src/components/filterCriteria/FilterCriteriaPanel/FilterCriteriaPanel.js
  src/components/filterCriteria/timePeriod/TimePeriod/TimePeriod.js
  src/components/filterCriteria/timePeriod/TimePeriod/TimePeriod.test.js
  src/components/filterCriteria/timePeriod/TimePeriod/TimePeriodRender.js
  src/components/filterCriteria/timePeriod/TimePeriodYear/TimePeriodYear.js
  src/utils/constants/allowances.js
  src/utils/dateValidation/dateValidation.js
Labels: Datateers

#108 Feature/1105 account name number filter
  manifest.yml
  src/components/FilterTags/FilterTags.js
  src/components/filterCriteria/AccountNameNumber/AccountNameNumber.js
  src/components/filterCriteria/AccountNameNumber/AccountNameNumber.test.js
  src/components/filterCriteria/FilterCriteriaPanel/FilterCriteriaPanel.js
  src/config.js
  src/store/actions/actionTypes.js
  src/store/actions/customDataDownload/filterCriteria.js
  src/store/reducers/customDataDownload/filterCriteria.js
  src/store/reducers/initialState.js
  src/utils/api/filterCriteriaApi.js
  src/utils/constants/allowances.js
  src/utils/selectors/filterCriteria.js
  src/utils/selectors/general.js
Labels: Datateers

#109 Bug/1783 year validation
  src/components/filterCriteria/timePeriod/TimePeriod/TimePeriod.test.js
  src/utils/dateValidation/dateValidation.js
Labels: Datateers

#110 Feature/1361 align data tables to react component
  package-lock.json
  package.json
  src/additional-scss/_global-overrides.scss
  src/additional-scss/_react-datatable-component-override.scss
  src/additional-scss/_variables.scss
  src/components/App/App.scss
  src/components/App/App.test.js
  src/components/Layout/Layout.scss
  src/components/customDataDownload/ManageDataDownload/ManageDataDownload.scss
  src/components/dataPreview/AnnualEmissions/AnnualEmissions.js
  src/components/dataPreview/DailyEmissions/DailyEmissions.js
  src/components/dataPreview/DataPreview/DataPreview.js
  src/components/dataPreview/DataPreview/DataPreview.test.js
  src/components/dataPreview/DataPreviewRender/DataPreviewRender.js
  src/components/dataPreview/DataPreviewRender/DataPreviewRender.scss
  src/components/dataPreview/HourlyEmissions/HourlyEmissions.js
  src/components/dataPreview/ManageDataPreview/ManageDataPreview.js
  src/components/dataPreview/MonthlyEmissions/MonthlyEmissions.js
  src/components/dataPreview/QuarterlyEmissions/QuarterlyEmissions.js
  src/config.js
  src/store/actions/actionTypes.js
  src/store/actions/customDataDownload/customDataDownload.js
  src/store/actions/customDataDownload/customDataDownload.test.js
  src/store/reducers/apiStatusReducer.test.js
  src/store/reducers/customDataDownload/customDataDownload.js
  src/store/reducers/initialState.js
  src/utils/api/dataPreviewApi.js
  src/utils/ensure-508/ensure-508.js
Labels: Datateers

#111 Bug/1485 firefox download
  src/components/customDataDownload/DownloadFileType/DownloadFileType.js
Labels: Datateers

#112 Bug/1790 white bg checkbox
  package-lock.json
  package.json
  src/additional-scss/_uswds-global-overrides.scss
Labels: Datateers

#113 feature/1617-desktop plus responsiveness to data preview
  src/additional-scss/_react-datatable-component-override.scss
  src/additional-scss/_variables.scss
  src/components/customDataDownload/ManageDataDownload/ManageDataDownload.scss
  src/components/dataPreview/DataPreviewRender/DataPreviewRender.js
  src/components/dataPreview/DataPreviewRender/DataPreviewRender.scss
  src/utils/selectors/emissions.js
Labels: Datateers
