Repository US-EPA-CAMD/easey-campd-ui, pull requests merged in 2022-02, with the labels that each got.

#293 Feature/2448 enhance spinners on campd to be 508 compliant
  src/components/RenderSpinner/RenderSpinner.js
  src/components/RenderSpinner/RenderSpinner.scss
  src/components/customDataDownload/DownloadFileType/DownloadFileType.js
  src/components/customDataDownload/ManageDataDownload/ManageDataDownload.js
  src/components/customDataDownload/ManageDataDownload/ManageDataDownload.test.js
  src/components/dataPreview/DataPreview/DataPreview.js
  src/components/dataPreview/DataPreviewRender/DataPreviewRender.js
  src/components/dataPreview/ManageDataPreview/ManageDataPreview.js
Labels: Datateers

#295 Feature/2448-Enhance-Spinners-On-CAMPD-To-Be-508-Compliant
  src/components/RenderSpinner/RenderSpinner.scss
Labels: Datateers

#296 Feature/2156 what is new box
  src/components/HomePage/HomePage.js
  src/components/HomePage/HomePage.scss
  src/components/HomePage/HomePage.test.js
Labels: Datateers

#297 Feature/2448-Enhance-Spinners-On-CAMPD-To-Be-508-Compliant
  src/components/RenderSpinner/RenderSpinner.js
  src/components/RenderSpinner/RenderSpinner.scss
  src/components/RenderSpinner/RenderSpinner.test.js
  src/components/customDataDownload/ManageDataDownload/ManageDataDownload.js
  src/components/dataPreview/DataPreviewRender/DataPreviewRender.test.js
Labels: Datateers

#298 Progress-Changes
  src/components/HomePage/HomePage.js
  src/config.js
Labels: Emissioners, Tech Team

#300 feature/stream-endpoints
  manifest-vars.prod.yml
  manifest-vars.staging.yml
  manifest-vars.test.yml
  manifest-vars.yml
  manifest.yml
  package.json
  src/components/customDataDownload/DownloadFileType/DownloadFileType.js
  src/components/dataPreview/ManageDataPreview/ManageDataPreview.js
  src/config.js
  src/utils/selectors/general.js
  yarn.lock
Labels: Datateers, Tech Team

#299 Bug/2582 account type filter logic
  src/utils/selectors/filterLogic.js
Labels: Datateers

#302 Feature/2533-cdd-helper-text-from-content-mgmt-api
  src/components/customDataDownload/ManageDataDownload/ManageDataDownload.test.js
  src/components/dataPreview/ManageDataPreview/ManageDataPreview.js
  src/components/dataPreview/ManageDataPreview/ManageDataPreview.test.js
Labels: Datateers

#303 Feature/2586-Mobile/-Tablet-Clear-Filter-Button-508-Issue
  src/components/RenderSpinner/RenderSpinner.scss
  src/components/customDataDownload/ManageDataDownload/ManageDataDownload.js
  src/components/dataPreview/ManageDataPreview/ManageDataPreview.js
  src/components/filterCriteria/FilterCriteriaMenu/FilterCriteriaMenu.js
Labels: Datateers

#304 Feature/2590-cdd-download-alert-508-issue
  src/components/dataPreview/ManageDataPreview/ManageDataPreview.js
Labels: Datateers

#305 Progress-Text
  package.json
  yarn.lock
Labels: Emissioners, Tech Team

#306 Feature/2606-Update-CAMPD-Logo
  src/components/SubHeader/SubHeader.js
  src/components/SubHeader/SubHeader.scss
Labels: Datateers

#307 Feature/2606-Update-CAMPD-Logo
  src/components/SubHeader/SubHeader.js
Labels: Datateers

#308 Bug/2609-CDD-Alert-And-Spinner
  src/components/customDataDownload/DownloadFileType/DownloadFileType.js
  src/components/dataPreview/ManageDataPreview/ManageDataPreview.js
Labels: Datateers

#309 Bug/2609-CDD-Alert-And-Spinner
  src/components/dataPreview/ManageDataPreview/ManageDataPreview.js
Labels: Datateers

#310 Bug/2609-CDD-Alert-And-Spinner
  src/components/customDataDownload/DownloadFileType/DownloadFileType.js
Labels: Datateers

#311 Feature/2527-ability-to-edit-home-page-static-content
  package.json
  src/components/App/App.test.js
  src/components/HomePage/HomePage.js
  src/components/HomePage/HomePage.scss
  src/components/HomePage/HomePage.test.js
  src/components/Layout/Layout.test.js
  src/components/SubHeader/SubHeader.test.js
  src/components/SubHeaderInfo/SubHeaderInfo.js
  src/components/SubHeaderInfo/SubHeaderInfo.test.js
  src/store/actions/customDataDownload/customDataDownload.test.js
  yarn.lock
Labels: Datateers

#312 Notifications-Switch
  manifest.yml
  src/components/ContactUsPage/ContactUsPage.js
  src/config.js
  src/utils/api/notificationsApi.js
  src/utils/api/notificationsApi.test.js
  src/utils/api/quartzApi.js
  src/utils/api/quartzApi.test.js
Labels: Datateers, Tech Team

#314 Feature/2585-display-download-functionality-and-alert-for-smaller-devices
  .gitignore
  src/components/customDataDownload/DownloadFileType/DownloadFileType.js
  src/components/customDataDownload/DownloadFileType/DownloadFileType.scss
  src/components/dataPreview/DataPreviewRender/DataPreviewRender.js
  src/components/dataPreview/DataPreviewRender/DataPreviewRender.scss
  src/components/dataPreview/ManageDataPreview/ManageDataPreview.js
Labels: Datateers

#315 feature/2615-data-preview-back-button-508-bug
  src/components/dataPreview/DataPreviewRender/DataPreviewRender.js
Labels: Datateers

#317 Feature/2585 display download functionality and alert at 200% zoom 508 issue
  src/components/dataPreview/DataPreviewRender/DataPreviewRender.js
Labels: Datateers

#318 Feature/2648-facility-filter-disabled
  src/utils/selectors/filterLogic.js
Labels: Datateers

#319 Feature/2650 update contact us error message
  src/components/ContactUsPage/ContactUsPage.js
Labels: Datateers

#320 Bug/allowance-transaction-filters
  src/components/filterCriteria/FilterCriteriaMenu/FilterCriteriaMenu.js
Labels: Datateers

#322 Feature/2530-edit-related-resources-static-content
  src/components/RelatedResources/RelatedResources.js
  src/components/RelatedResources/RelatedResources.test.js
Labels: Datateers

#323 Bug/vintage year and facility filters
  src/components/filterCriteria/Facility/Facility.js
  src/components/filterCriteria/timePeriod/TimePeriodComboBox/TimePeriodComboBox.js
Labels: Datateers

#331 Feature/2531-Provide-EPA-The-Ability-To-Edit-Static-Content-On-FAQs-Page
  src/components/FaqPage/FaqsPage.js
  src/components/FaqPage/FaqsPage.test.js
  src/components/RelatedResources/RelatedResources.test.js
  src/components/customDataDownload/DownloadFileType/DownloadFileType.test.js
Labels: Datateers

#332 Feature/2532 contact us content manager
  src/components/ContactUsPage/ContactUsPage.js
  src/components/ContactUsPage/ContactUsPage.scss
  src/components/ContactUsPage/ContactUsPage.test.js
Labels: Datateers

#333 Feature/2635-mats-data-on-cdd
  src/components/RelatedResources/RelatedResources.test.js
  src/components/customDataDownload/ManageDataDownload/ManageDataDownload.js
  src/components/filterCriteria/Facility/Facility.js
  src/components/filterCriteria/FilterCriteriaMenu/FilterCriteriaMenu.js
  src/components/filterCriteria/FilterCriteriaPanel/FilterCriteriaPanel.js
  src/components/filterCriteria/timePeriod/TimePeriod/TimePeriod.js
  src/components/filterCriteria/timePeriod/TimePeriod/TimePeriodRender.js
  src/components/filterCriteria/timePeriod/TimePeriodFullDate/TimePeriodFullDate.js
  src/utils/constants/customDataDownload.js
  src/utils/constants/mats.js
Labels: Datateers

#334 feature/2635-mats-data-on-cdd
  src/utils/constants/mats.js
Labels: Datateers

#335 Feature/1653-Auto-Collapse-Menu-Items
  src/components/SubHeader/SubHeader.js
  src/components/SubHeaderNav/SubHeaderNav.js
  src/utils/hooks/useClickoutClose.js
Labels: Datateers

#337 Feature/2559 glossary buttons content manager
  src/components/GlossaryPage/GlossaryPage.js
  src/components/GlossaryPage/GlossaryPage.test.js
Labels: Datateers

#338 Feature/2541-adjust-data-preview-column-spacing
  src/additional-scss/_react-datatable-component-override.scss
  src/components/dataPreview/DataPreview/DataPreview.js
  src/utils/constants/dataPreviewCol.js
Labels: Datateers

#340 Feature/2516-Display-Spinners-While-Filter-Logic-Is-Engaged
  src/components/RenderSpinner/RenderSpinner.js
  src/components/RenderSpinner/RenderSpinner.test.js
  src/components/customDataDownload/DownloadFileType/DownloadFileType.js
  src/components/customDataDownload/DownloadFileType/DownloadFileType.test.js
  src/components/customDataDownload/ManageDataDownload/ManageDataDownload.js
  src/components/dataPreview/DataPreview/DataPreview.js
  src/components/dataPreview/DataPreviewRender/DataPreviewRender.js
  src/components/dataPreview/ManageDataPreview/ManageDataPreview.js
  src/store/reducers/initialState.js
  src/utils/selectors/filterLogic.js
Labels: Datateers
